select * from EXAMPLE_DB.EXAMPLE_SCHEMA.EMPLOYEES;

DEV (FULL -- TABLE, VIEW, ) - Full access
QA, PROD -- READONLY

--
GitHub Token is requied.

https://snowflake.zoom.us/w/82172484354?tk=kVo72dLLEN1Pqn7VNtcPe_y4YOTHf-xE64hphBcYNp8.DQkAAAATIdybAhZ0NkE1a1pHUlNZR1RPeHYybi1zd25RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&pwd=1ZeqjQf5sb0ZvtULbUcqcNZy152RsX.1&uuid=WN_f_b3x2rcSl6TPYAdUC5VEw